#Use ChatGPT to generate a sample nested dictionary structure for a BookMyShow movie ticket booking (including movie name, showtime, seat numbers, and user info), then implement code in Python to print the seat numbers from this structure.<br><br><em><strong>Hint:</strong> Paste the dictionary generated by ChatGPT directly into your code.</em>
booking = {
    "movie": {
        "name": "Jawan",
        "showtime": "7:00 PM"
    },
    "seats": ["A10", "A11", "A12"],
    "user": {
        "name": "Kavita",
        "email": "kavita@example.com"
    }
}

print("Seat numbers:", booking["seats"])